import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { IssuesProvider } from "@/lib/IssuesContext";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mechanikai | Jira",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <IssuesProvider>{children}</IssuesProvider>
      </body>
    </html>
  );
}
