import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Link from "next/link";
import { IssuesProvider } from "@/lib/IssuesContext";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mechanikai | Jira",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <header className="header">
          <div className="header__inner">
            <Link href="/" className="header__logo-link" aria-label="Go to home page">
              <img src="/logo.svg" alt="Svenheim" className="header__logo" />
            </Link>
            <div className="header__right">Mechanikai Jira</div>
          </div>
        </header>
        <IssuesProvider>{children}</IssuesProvider>
      </body>
    </html>
  );
}
